# deploy development branch

name: deploy-to-dev

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploy to dev env
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.SSH_HOST_IP }}
          ssh-port: ${{ secrets.SSH_HOST_PORT }}
      - name: Run deploy script on host
        run: |
          ssh -t -p ${{ secrets.SSH_HOST_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST_IP }} << EOF
            cd /home/${{ secrets.SSH_USER }}/aed-mapa-dev/
            git pull
            rsync --update --recursive --delete \
              --exclude '*.py' --exclude '*.geojson' --exclude '.git*' --exclude '*.json' \
              --verbose /home/${{ secrets.SSH_USER }}/aed-mapa-dev/ /var/www/dev/
          EOF
