# deploy main branch

name: deploy-to-prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to prod env
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.SSH_HOST_IP }}
          ssh-port: ${{ secrets.SSH_HOST_PORT }}
      - name: Run deploy script on host
        run: ssh -t -p ${{ secrets.SSH_HOST_PORT }} -l ${{ secrets.SSH_USER }} ${{ secrets.SSH_HOST_IP }} /home/${{ secrets.SSH_USER }}/deploy_prod.sh 2> deploy_prod_err.txt
